/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as LoginRouteImport } from './routes/login'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BoardsNewRouteImport } from './routes/boards.new'
import { Route as BoardsBoardIdRouteImport } from './routes/boards.$boardId'
import { Route as BoardsBoardIdEditRouteImport } from './routes/boards.$boardId.edit'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BoardsNewRoute = BoardsNewRouteImport.update({
  id: '/boards/new',
  path: '/boards/new',
  getParentRoute: () => rootRouteImport,
} as any)
const BoardsBoardIdRoute = BoardsBoardIdRouteImport.update({
  id: '/boards/$boardId',
  path: '/boards/$boardId',
  getParentRoute: () => rootRouteImport,
} as any)
const BoardsBoardIdEditRoute = BoardsBoardIdEditRouteImport.update({
  id: '/edit',
  path: '/edit',
  getParentRoute: () => BoardsBoardIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/boards/$boardId': typeof BoardsBoardIdRouteWithChildren
  '/boards/new': typeof BoardsNewRoute
  '/boards/$boardId/edit': typeof BoardsBoardIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/boards/$boardId': typeof BoardsBoardIdRouteWithChildren
  '/boards/new': typeof BoardsNewRoute
  '/boards/$boardId/edit': typeof BoardsBoardIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/boards/$boardId': typeof BoardsBoardIdRouteWithChildren
  '/boards/new': typeof BoardsNewRoute
  '/boards/$boardId/edit': typeof BoardsBoardIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/signup'
    | '/boards/$boardId'
    | '/boards/new'
    | '/boards/$boardId/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/signup'
    | '/boards/$boardId'
    | '/boards/new'
    | '/boards/$boardId/edit'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/signup'
    | '/boards/$boardId'
    | '/boards/new'
    | '/boards/$boardId/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  SignupRoute: typeof SignupRoute
  BoardsBoardIdRoute: typeof BoardsBoardIdRouteWithChildren
  BoardsNewRoute: typeof BoardsNewRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/boards/new': {
      id: '/boards/new'
      path: '/boards/new'
      fullPath: '/boards/new'
      preLoaderRoute: typeof BoardsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/boards/$boardId': {
      id: '/boards/$boardId'
      path: '/boards/$boardId'
      fullPath: '/boards/$boardId'
      preLoaderRoute: typeof BoardsBoardIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/boards/$boardId/edit': {
      id: '/boards/$boardId/edit'
      path: '/edit'
      fullPath: '/boards/$boardId/edit'
      preLoaderRoute: typeof BoardsBoardIdEditRouteImport
      parentRoute: typeof BoardsBoardIdRoute
    }
  }
}

interface BoardsBoardIdRouteChildren {
  BoardsBoardIdEditRoute: typeof BoardsBoardIdEditRoute
}

const BoardsBoardIdRouteChildren: BoardsBoardIdRouteChildren = {
  BoardsBoardIdEditRoute: BoardsBoardIdEditRoute,
}

const BoardsBoardIdRouteWithChildren = BoardsBoardIdRoute._addFileChildren(
  BoardsBoardIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  SignupRoute: SignupRoute,
  BoardsBoardIdRoute: BoardsBoardIdRouteWithChildren,
  BoardsNewRoute: BoardsNewRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
